// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum, pgTable as table } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types } from "@duneanalytics/sim-idx";

export const debtPositionIsLiquidatable = table("debt_position_is_liquidatable", {
  chainId: db.uint64('chain_id'),
  timestamp: db.uint256('timestamp'),
  market: db.address('market'),
  debtPositionId: db.uint256('debt_position_id'),
  collateralRatio: db.uint256('collateral_ratio'),
  loanStatus: db.uint8('loan_status'),
})
